### ISSUE TITLE
check-ntpoffset.go - Chrony support?

### ISSUE THREAD

**Issue by chris-x86-64** [mackerelio/go-check-plugins#165]
Hi,

Recent RHEL-type distributions (namely RHEL 7) use `chronyd`, replacing `ntpd`.
However, command `ntpq` is designed to be used in conjunction with `crond` so if `chronyd` is running in place of `ntpd`, `ntpq` cannot be used because the connection cannot be established. `chronyc` is used instead.

This prevents `check-ntpoffset.go` from working on boxes without a working `ntpd` or the command `ntpq`.
The origin of the problem is most likely https://github.com/mackerelio/go-check-plugins/blob/master/check-ntpoffset/lib/check-ntpoffset.go#L59 this line.

May I ask for Chrony support in `check-ntpoffset.go`?
Thanks.

**Comment by Songmu** [comment]
Thank you for reporting.

I fixed it at #166, and it will be released on next version.

**Comment by Songmu** [comment]
Released as v0.10.3. Thanks!
