### ISSUE TITLE
check_http.go - Override statuses?

### ISSUE THREAD

**Issue by chris-x86-64** [mackerelio/go-check-plugins#181]
Hi,

I'm currently working on a web server with IP blacklist enabled.
If a blacklisted client accesses it, it should return 403.

I would like to make sure such a control is indeed working-- in order to achieve that, I want `check_http` to return `OK` when the web server returns 403 under a certain condition (Particularly #182 ) and `CRITICAL` when it returns anything else, including 200 OK.

I'm concerned that it might be a long way to go, but I'd be very happy to use `check_http` in this way.
Thanks.

**Comment by syou6162** [comment]
@chris-x86-64 I merged #183 (Thanks @mattn!), so you can use `--status`(or `-s`) option to override statuses you want with master branch.
