### ISSUE TITLE
Proposal: `--count-by` option for check-log plugin

### ISSUE THREAD

**Issue by Cside** [mackerelio/go-check-plugins#232]
I want to fire an alert if the unique count of IP exceeds N cases.
How about adding an option `--count-by` to check-log plugin ?

Bellow is my image to use:
```
--count-by 'IP:([0-9\.])+\t'
```

On the other hand, like the `awk` , an interface that allows us to choose separator and the number also seems good.

**Comment by mattn** [comment]
What is the condition for alert? Need to add option to specify N?
