### ISSUE TITLE
Binary for windows

### ISSUE THREAD

**Issue by imweijh** [mackerelio/go-check-plugins#244]
Hi
Will provide binary for windows ?

Thanks.

**Comment by daiksy** [comment]
Hi,

It is included in mackerel-agent's msi.
https://mackerel.io/docs/entry/howto/install-agent/msi

- List of included plugins
  - https://github.com/mackerelio/mackerel-agent/blob/master/wix/pluginlist.txt

**Comment by imweijh** [comment]
Thanks
