### ISSUE TITLE
New checks

### ISSUE THREAD

**Issue by n-rodriguez** [mackerelio/go-check-plugins#299]
Hi there!

First I'd like to say that I really appreciate this project :heart: 

It reminds me this one : [uutils/coreutils](https://github.com/uutils/coreutils) and I think both are very good initiatives.

The install is easy thanks to the `deb` package and I achieved to build a new package with 3 news checks :

* check-mem
* check-swap
* check-diff-time

and added a `--password` flag on `check-redis`.

Would you like a PR to add this checks and feature?

Thank you!

**Comment by lufia** [comment]
@n-rodriguez Thank you!

We accept new features or bug fixes for existant plugins, so we will review new `-password` flag of check-redis.

But currently we are not accepting new plugin on this repository.
Please register the new plugin on https://github.com/mackerelio/plugin-registry.
https://mackerel.io/blog/entry/feature/20171116#Pull-Requests-to-the-existing-central-repository
