### ISSUE TITLE
check-ssh: add option to disable auth check (same as Nagios)

### ISSUE THREAD

**Issue by maxadamo** [mackerelio/go-check-plugins#453]
I noticed that the Nagios check-ssh does not try to authenticate and it checks the socket only. 
If it's not possible for you to make it the same, would it be possible to add an option like: `--no-auth-check` ?

**Comment by susisu** [comment]
Hi,

This is not a project for providing complete alternatives to the Nagios plugins, so we don't have strong intention to implement the very same feature.
But, if you are interested, we are happy to accept a PR for this.
