### ISSUE TITLE
check-disk fails on GitHub Action

### ISSUE THREAD

**Issue by Arthur1** [mackerelio/go-check-plugins#625]

**Comment by lufia** [comment]
I can reproduce this bug.

In my Linux box, **check-disk** stops with *EPERM* error when it access `/run/user/<uid>/doc` mountpoint that is mounted by **fuse.portal** type.

```console
$ uname -a
Linux lufia-pc 5.18.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 12 Jul 2022 15:40:51 +0000 x86_64 GNU/Linux
```

According to https://bugzilla.redhat.com/show_bug.cgi?id=1913358 **fuse.portal** should handle as a dummy device, like **kernfs**.
